"""Add column to table 'accounts'

Revision ID: fb027df22c8f
Revises: 3c5071b79e17
Create Date: 2021-09-16 10:06:54.112176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb027df22c8f'
down_revision = '3c5071b79e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_name')
    op.drop_column('accounts', 'first_name')
    # ### end Alembic commands ###
